"""Prospective multi-model replication analysis for the VizWiz audit."""

from __future__ import annotations

import json
import math
from pathlib import Path

import numpy as np
import pandas as pd

from .analysis import SCORE_COLUMNS
from .inference import MODEL_SPECS, REPLICATION_MODEL_KEYS
from .metrics import certify_selective_threshold, learn_selective_threshold

RISK_TARGET = 0.10
FIT_RISK = 0.05
FAMILY_DELTA = 0.05
PER_MODEL_DELTA = FAMILY_DELTA / 2
SPLIT_COUNTS = (860, 860, 2581)
SENSITIVITY_SEEDS = tuple(range(1000, 1100))


def _tex_decimal(value: object, digits: int = 4) -> str:
    number = float(value)
    return f"{number:.{digits}f}" if math.isfinite(number) else "--"


def _tex_percent(value: object, digits: int = 1) -> str:
    number = float(value)
    return f"{100.0 * number:.{digits}f}\\%" if math.isfinite(number) else "--"


def _write_replication_macros(
    frame: pd.DataFrame,
    summaries: pd.DataFrame,
    sensitivity: pd.DataFrame,
    path: Path,
) -> None:
    """Write deterministic TeX macros from the frozen replication tables."""

    lines = ["% Generated by sash_audit.replication; do not edit."]
    natural_n = int((frame["regime"] == "natural").sum() / len(REPLICATION_MODEL_KEYS))
    shift_n = int((frame["regime"] == "shift").sum() / len(REPLICATION_MODEL_KEYS))
    lines.extend(
        [
            rf"\renewcommand{{\RepRows}}{{{len(frame)}}}",
            rf"\renewcommand{{\RepNaturalN}}{{{natural_n}}}",
            rf"\renewcommand{{\RepShiftN}}{{{shift_n}}}",
            rf"\renewcommand{{\RepSensitivityN}}{{{len(SENSITIVITY_SEEDS)}}}",
        ]
    )
    for regime, prefix in (("natural", "Natural"), ("shift", "Shift")):
        subset = frame[frame["regime"] == regime]
        for split in ("fit", "certification", "test"):
            count = int(
                (subset["evaluation_split"] == split).sum()
                / len(REPLICATION_MODEL_KEYS)
            )
            lines.append(rf"\renewcommand{{\Rep{prefix}{split.capitalize()}N}}{{{count}}}")

    fields = {
        "Vqa": lambda row: _tex_percent(row["test_answered_vqa_accuracy"]),
        "Threshold": lambda row: _tex_decimal(row["fit_threshold"]),
        "CertErrorsAccepted": lambda row: (
            f"{int(row['certification_errors'])}/{int(row['certification_accepted'])}"
        ),
        "CertUpper": lambda row: _tex_percent(row["certification_upper_bound"]),
        "CertDecision": lambda row: "Pass" if bool(row["certified"]) else "Fail",
        "TestCoverage": lambda row: _tex_percent(row["test_coverage"]),
        "TestErrorsAccepted": lambda row: f"{int(row['test_errors'])}/{int(row['test_accepted'])}",
        "TestRisk": lambda row: _tex_percent(row["test_entirely_wrong_risk"]),
    }
    prefixes = (("smolvlm", "Smol"), ("llava_onevision", "Llava"))
    for model_key, model_prefix in prefixes:
        for regime, regime_prefix in (("natural", "Natural"), ("shift", "Shift")):
            row = summaries[
                (summaries["model_key"] == model_key)
                & (summaries["regime"] == regime)
            ].iloc[0]
            for field, formatter in fields.items():
                macro = rf"\renewcommand{{\{model_prefix}{regime_prefix}{field}}}"
                lines.append(f"{macro}{{{formatter(row)}}}")

        subset = sensitivity[sensitivity["model_key"] == model_key]
        sensitivity_fields = {
            "rate": float(subset["certified"].mean()),
            "upper": float(subset["certification_upper_bound"].median()),
            "coverage": float(subset["test_coverage"].median()),
            "risk": float(subset["test_entirely_wrong_risk"].median()),
        }
        for field, value in sensitivity_fields.items():
            formatter = _tex_percent
            lines.append(
                rf"\renewcommand{{\Rep{model_prefix}Sensitivity{field.capitalize()}}}{{{formatter(value)}}}"
            )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _split_counts(total: int) -> tuple[int, int, int]:
    if total == sum(SPLIT_COUNTS):
        return SPLIT_COUNTS
    fit = max(1, int(round(total * 0.20)))
    certification = max(1, int(round(total * 0.20)))
    test = total - fit - certification
    if test < 1:
        raise ValueError("replication sensitivity requires at least three cases")
    return fit, certification, test


def _substantive(frame: pd.DataFrame) -> np.ndarray:
    return (
        (frame["normalized_answer"].astype(str) != "unanswerable")
        & (frame["generated_tokens"].to_numpy(int) > 0)
    ).to_numpy(bool)


def validate_replication_frame(
    frame: pd.DataFrame,
    *,
    model_keys: tuple[str, ...] = REPLICATION_MODEL_KEYS,
    strict_counts: bool = False,
) -> None:
    """Validate a paired replication frame without changing the original audit."""

    expected_models = set(model_keys)
    actual_models = set(frame["model_key"].astype(str))
    if actual_models != expected_models:
        raise ValueError(
            f"replication predictions must contain {sorted(expected_models)}, "
            f"found {sorted(actual_models)}"
        )
    for model_key in model_keys:
        model_id, revision = MODEL_SPECS[model_key]
        subset = frame[frame["model_key"] == model_key]
        if set(subset["model_id"]) != {model_id} or set(subset["model_revision"]) != {revision}:
            raise ValueError(f"{model_key} predictions do not match the pinned checkpoint")

    if set(frame["regime"]) != {"natural", "shift"}:
        raise ValueError("replication predictions must contain natural and shift regimes")
    if not set(frame["evaluation_split"]).issubset({"fit", "certification", "test"}):
        raise ValueError("unexpected evaluation split")
    for regime in ("natural", "shift"):
        shift_counts = (300, 300, 600)
        for split, expected in zip(
            ("fit", "certification", "test"), SPLIT_COUNTS, strict=True
        ):
            subset = frame[
                (frame["regime"] == regime) & (frame["evaluation_split"] == split)
            ]
            ids_by_model = {
                key: set(subset.loc[subset["model_key"] == key, "case_id"])
                for key in model_keys
            }
            if any(not ids for ids in ids_by_model.values()):
                raise ValueError(f"missing {regime}/{split} replication predictions")
            first_ids = ids_by_model[model_keys[0]]
            if any(ids != first_ids for ids in ids_by_model.values()):
                raise ValueError(f"model case IDs differ for {regime}/{split}")
            if strict_counts:
                expected_count = expected if regime == "natural" else shift_counts[
                    ("fit", "certification", "test").index(split)
                ]
                if any(len(ids) != expected_count for ids in ids_by_model.values()):
                    raise ValueError(f"unexpected count in {regime}/{split}")


def _pipeline_row(model_key: str, regime: str, frame: pd.DataFrame) -> dict[str, object]:
    fit = frame[frame["evaluation_split"] == "fit"]
    certification = frame[frame["evaluation_split"] == "certification"]
    test = frame[frame["evaluation_split"] == "test"]
    score_column = SCORE_COLUMNS["likelihood"]
    fit_eligible = _substantive(fit)
    cert_eligible = _substantive(certification)
    test_eligible = _substantive(test)
    threshold, fit_empirical_risk, fit_accepted = learn_selective_threshold(
        fit[score_column],
        fit["entirely_wrong"],
        risk_limit=FIT_RISK,
        eligible=fit_eligible,
    )
    cert = certify_selective_threshold(
        certification[score_column],
        certification["entirely_wrong"],
        threshold=threshold,
        alpha=RISK_TARGET,
        delta=PER_MODEL_DELTA,
        eligible=cert_eligible,
    )
    accepted = test_eligible & (test[score_column].to_numpy(float) >= threshold)
    scores = test.loc[accepted, "vqa_score"].to_numpy(float)
    return {
        "model_key": model_key,
        "model_id": MODEL_SPECS[model_key][0],
        "model_revision": MODEL_SPECS[model_key][1],
        "regime": regime,
        "score": "likelihood",
        "fit_threshold": threshold,
        "fit_empirical_risk": fit_empirical_risk,
        "fit_accepted": fit_accepted,
        "certification_accepted": cert.accepted,
        "certification_errors": cert.errors,
        "certification_upper_bound": cert.upper_bound,
        "certified": cert.certified,
        "test_accepted": int(accepted.sum()),
        "test_coverage": float(accepted.mean()) if len(test) else math.nan,
        "test_errors": int((scores == 0).sum()),
        "test_entirely_wrong_risk": float((scores == 0).mean()) if len(scores) else math.nan,
        "test_answered_vqa_accuracy": float(scores.mean()) if len(scores) else math.nan,
    }


def analyze_replication(
    frame: pd.DataFrame,
    *,
    model_keys: tuple[str, ...] = REPLICATION_MODEL_KEYS,
    strict_counts: bool = False,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Return frozen natural/shift summaries and predeclared split sensitivity."""

    validate_replication_frame(frame, model_keys=model_keys, strict_counts=strict_counts)
    summaries: list[dict[str, object]] = []
    for model_key in model_keys:
        for regime in ("natural", "shift"):
            subset = frame[
                (frame["model_key"] == model_key) & (frame["regime"] == regime)
            ]
            summaries.append(_pipeline_row(model_key, regime, subset))

    natural = frame[frame["regime"] == "natural"].copy()
    sensitivity_counts = _split_counts(
        int(natural[["case_id"]].drop_duplicates().shape[0])
    )
    sensitivity: list[dict[str, object]] = []
    for seed in SENSITIVITY_SEEDS:
        case_ids = (
            natural[["case_id"]]
            .drop_duplicates()
            .sort_values("case_id")["case_id"]
            .to_numpy()
        )
        permutation = np.random.default_rng(seed).permutation(case_ids)
        split_by_case = {
            case_id: split
            for split, ids in zip(
                ("fit", "certification", "test"),
                (
                    permutation[: sensitivity_counts[0]],
                    permutation[sensitivity_counts[0] : sum(sensitivity_counts[:2])],
                    permutation[sum(sensitivity_counts[:2]) :],
                ),
                strict=True,
            )
            for case_id in ids
        }
        for model_key in model_keys:
            model = natural[natural["model_key"] == model_key].copy()
            model["evaluation_split"] = model["case_id"].map(split_by_case)
            row = _pipeline_row(model_key, "natural", model)
            sensitivity.append(
                {
                    "seed": seed,
                    "model_key": model_key,
                    "certified": row["certified"],
                    "certification_upper_bound": row["certification_upper_bound"],
                    "test_coverage": row["test_coverage"],
                    "test_entirely_wrong_risk": row["test_entirely_wrong_risk"],
                }
            )
    return pd.DataFrame(summaries), pd.DataFrame(sensitivity)


def write_replication_analysis(
    frame: pd.DataFrame,
    output_dir: Path,
    *,
    model_keys: tuple[str, ...] = REPLICATION_MODEL_KEYS,
    strict_counts: bool = False,
) -> dict[str, str]:
    """Write machine-readable replication results and immutable metadata."""

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    summaries, sensitivity = analyze_replication(
        frame, model_keys=model_keys, strict_counts=strict_counts
    )
    summary_path = output_dir / "replication_metrics.csv"
    sensitivity_path = output_dir / "split_sensitivity.csv"
    metadata_path = output_dir / "replication_metadata.json"
    macro_path = output_dir / "replication_results.tex"
    summaries.to_csv(summary_path, index=False)
    sensitivity.to_csv(sensitivity_path, index=False)
    metadata = {
        "model_keys": list(model_keys),
        "risk_target": RISK_TARGET,
        "fit_risk": FIT_RISK,
        "family_delta": FAMILY_DELTA,
        "per_model_delta": PER_MODEL_DELTA,
        "split_counts": SPLIT_COUNTS,
        "sensitivity_seeds": [SENSITIVITY_SEEDS[0], SENSITIVITY_SEEDS[-1]],
        "rows": int(len(frame)),
    }
    metadata_path.write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")
    _write_replication_macros(frame, summaries, sensitivity, macro_path)
    return {
        "metrics": str(summary_path),
        "sensitivity": str(sensitivity_path),
        "metadata": str(metadata_path),
        "latex": str(macro_path),
    }


__all__ = [
    "analyze_replication",
    "validate_replication_frame",
    "write_replication_analysis",
]
